language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: 
        - PIP=pip
        - CIBW_SKIP="cp27-* cp33-* cp34-*"
        - CIBW_BEFORE_BUILD="pip install -r test-requirements.txt"
    - os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBWSKIP="cp27-* cp33-* cp34-*"
        - CIBW_BEFORE_BUILD="pip install -r test-requirements.txt"

script:
  - $PIP install -r test-requirements.txt
  - $PIP install cibuildwheel==0.9.2
  - cibuildwheel --output-dir wheelhouse

notifications:
  email:
    on_success: never
