language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: 
        - PIP=pip
        - CIBW_SKIP="cp27-* cp33-* cp34-*"
        - CIBW_BEFORE_BUILD="python -m pip install -U pip && pip install ."
    - os: osx
      language: generic
      env:
        - PIP=pip
        - CIBWSKIP="cp27-* cp33-* cp34-*"
        - CIBW_BEFORE_BUILD="python -m pip install -U pip && pip install ."

script:
  - $PIP install -r test-requirements.txt
  - $PIP install cibuildwheel==0.10
  - python -m pip install -U pip
  - $PIP install .
  - cibuildwheel --output-dir wheelhouse

notifications:
  email:
    on_success: never
