name: CI


on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
    paths-ignore:
      - '**/*.rst'
      - '**/*.md'
      - .gitignore
      - .travis.yml
      - LICENSE
jobs:
  tests:

    runs-on: windows-latest
      strategy:
        matrix:
          python: ['3.5', '3.6', '3.7', '3.8']
          arch: ['x86', 'x64']
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.arch }}
    - name: install requirements
      run: python -m pip install -r test-requirements.txt
    - run: python -m pip install cibuildwheel
    - run: python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_SKIP: "cp27-* cp33-* cp34-*"
        CIBW_BEFORE_BUILD: "python -m pip install -r test-requirements.txt"
      
      
      
