name: CI


on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
    paths-ignore:
      - '**/*.rst'
      - '**/*.md'
      - .gitignore
      - .travis.yml
      - LICENSE
jobs:
  tests:

    runs-on: windows-latest
    strategy:
        matrix:
          python: ['3.5', '3.6', '3.7']
          arch: ['x86', 'x64']
    steps:
    - uses: actions/checkout@v1
    - run: git submodule update --init
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.arch }}
    - name: install requirements
      run: python -m pip install -r test-requirements.txt
    - run: python setup.py build_ext
      
      
      
